title: 3D Printing Quick Reference
description: >- # this means to ignore newlines until "baseurl:"
  Spark Makerspace 3D Printing Quick Reference
baseurl: "/" 
url: "https://3d-printing-guide.sparkmakerspace.org"

theme: minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
